-- MySQL Script generated by MySQL Workbench
-- Seg 11 Jul 2016 19:37:04 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema migration_ov
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema migration_ov
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `migration_ov` DEFAULT CHARACTER SET utf8 ;
USE `migration_ov` ;

-- -----------------------------------------------------
-- Table `migration_ov`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `migration_ov`.`roles` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_level` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `migration_ov`.`clinics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `migration_ov`.`clinics` (
  `clinic_id` INT NOT NULL AUTO_INCREMENT,
  `clinic_name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`clinic_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Tabela clinica onde ficara armazendo o nome da clinica e seu respectivo id associado a tabela users';


-- -----------------------------------------------------
-- Table `migration_ov`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `migration_ov`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_user` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `user_name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `user_email` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `user_password` CHAR(128) CHARACTER SET 'utf8' NOT NULL,
  `user_session_id` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `user_permissions` LONGTEXT CHARACTER SET 'utf8' NOT NULL,
  `user_role_id` INT(11) NOT NULL,
  `user_status` INT(2) NOT NULL,
  `user_clinic_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_clinic_id`),
  INDEX `users_user_role_id_idx` (`user_role_id` ASC),
  INDEX `users_user_clinic_id_idx` (`user_clinic_id` ASC),
  CONSTRAINT `users_user_role_id`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `migration_ov`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `users_user_clinic_id`
    FOREIGN KEY (`user_clinic_id`)
    REFERENCES `migration_ov`.`clinics` (`clinic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `migration_ov`.`login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `migration_ov`.`login_attempts` (
  `login_attempts_id` INT(11) NOT NULL AUTO_INCREMENT,
  `login_attempts_users_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`login_attempts_id`, `login_attempts_users_id`),
  INDEX `login_attempts_login_attempts_users_id_idx` (`login_attempts_users_id` ASC),
  CONSTRAINT `login_attempts_login_attempts_users_id`
    FOREIGN KEY (`login_attempts_users_id`)
    REFERENCES `migration_ov`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `migration_ov`.`recoveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `migration_ov`.`recoveries` (
  `recovery_id` INT(11) NOT NULL AUTO_INCREMENT,
  `recovery_users_id` INT(11) NOT NULL,
  `recovery_token` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `recovery_status` INT(1) NOT NULL,
  PRIMARY KEY (`recovery_id`, `recovery_users_id`),
  INDEX `passwords_users_id_idx` (`recovery_users_id` ASC),
  CONSTRAINT `passwords_users_id`
    FOREIGN KEY (`recovery_users_id`)
    REFERENCES `migration_ov`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
