INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (2, 'Cirurgia e Traumatologia Buco Maxilo Faciais');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (3, 'Clínica Geral');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (4, 'Dentistica');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (5, 'Dentistica Restauradora');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (6, 'Disfuncao Temporo-Mandibular e Dor-Orofacial');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (7, 'Endodontia');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (8, 'Estomatologia');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (9, 'Implantodontia');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (10, 'Odontogeriatria');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (11, 'Odontologia do Trabalho');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (12, 'Odontologia em Saude Coletiva');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (13, 'Odontologia Legal');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (14, 'Odontologia para Pacientes com Necessidades Especiais');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (15, 'Odontopediatria');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (16, 'Ortodontia');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (17, 'Ortodontia e Ortopedia Facial');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (18, 'Ortopedia Funcional dos Maxilares');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (19, 'Patologia Bucal');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (20, 'Periodontia');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (21, 'Protese Buco Maxilo Facial');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (22, 'Protese Dentaria');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (23, 'Radiologia');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (24, 'Radiologia Odontologica e Imaginologia');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (25, 'Saúde Coletiva');
INSERT INTO `migration_ov`.`users_esp` (`esp_id`, `esp`) VALUES (1, 'Não informado');
